site_name: C&S Cottage



nav:
  - 跳跳之家:
    - Timeaxis: cscottage/index.md
    - 我们的窝: cscottage/cscottage/wenxinxiaowo.md
  - 时光手账:
    - 时间印记: shiguang/shiguang/sjyj.md
    - 校园记忆:
      - 校园记忆: shiguang/shiguang/xyjy.md
      - 毕业快乐: shiguang/shiguang/bykl.md
    - With You:
      - 2017-10-14: shiguang/shiguang/sz20171014.md
      - 2018-12-09: shiguang/shiguang/sz20181209.md
      - 2018-12-30: shiguang/shiguang/sz20181230.md
      - 2019-02-17: shiguang/shiguang/sz20190217.md
      - 2019-03-08: shiguang/shiguang/sz20190308.md
      - 2019-03-23: shiguang/shiguang/sz20190323.md
      - 2019-04-05: shiguang/shiguang/sz20190405.md
      - 2019-04-10: shiguang/shiguang/sz20190410.md
      - 2019-04-23: shiguang/shiguang/sz20190423.md
      - 2019-05-04: shiguang/shiguang/sz20190504.md
      - 2019-06-07: shiguang/shiguang/sz20190607.md
      - 2019-06-22: shiguang/shiguang/sz20190622.md
      - 2019-12-15: shiguang/shiguang/sz20191215.md
      - 2019-12-24: shiguang/shiguang/sz20191224.md
    - 日常:
      - 2018-12-16: shiguang/shiguang/rc20181216.md
      - 2018-12-31: shiguang/shiguang/rc20181231.md
      - 2019-01-01: shiguang/shiguang/rc20190101.md
      - 2019-03-30: shiguang/shiguang/rc20190330.md
      - 2019-06-30: shiguang/shiguang/rc20190630.md
      - 2019-07-14: shiguang/shiguang/rc20190714.md
      - 2019-08-20: shiguang/shiguang/rc20190820.md
      - 2019-12-08: shiguang/shiguang/rc20191208.md
      - 2020-01-01: shiguang/shiguang/rc20200101.md
      - 2020-04-04: shiguang/shiguang/rc20200404.md
      - 2020-01-01: shiguang/shiguang/rc20200101.md
      - 2020-01-26~02-05: shiguang/shiguang/rc20200126.md
      - 2022-12: shiguang/shiguang/rc202212.md
  - 与君同游:
    - 与君同游: trip/index.md
    - 山东:
      - 青岛: trip/shandong/qingdao.md
      - 烟台: trip/shandong/yantai.md
    - 江苏:
      - 苏州: trip/jiangsu/suzhou.md
      - 南京: trip/jiangsu/nanjing.md
      - 无锡: trip/jiangsu/wuxi.md
    #  - 南通:
    - 上海:
      - 上海: trip/shanghai/shanghai.md
    - 浙江:
      - 杭州: trip/zhejiang/hangzhou.md
      - 嘉兴: trip/zhejiang/jiaxing.md
      - 嵊泗列岛: trip/zhejiang/shengsi.md
      - 丽水: trip/zhejiang/lishui.md
    - 云南:
    #  - 昆明:
      - 大理: trip/yunnan/dali.md
      - 丽江: trip/yunnan/lijiang.md
    - 海南:
      - 三亚: trip/hainan/sanya.md
    - 陕西: 
      - 西安: trip/shanxi/xian.md
    - 辽宁:
      - 大连: trip/liaoning/dalian.md
  - 诗情画意:
    - 诗情画意: shihua/index.md
    - 诗情:
      - 三句诗: shihua/shi/sanjushi.md
      - 写给妈妈: shihua/shi/tomama.md
      - 鹊桥仙: shihua/shi/queqiaoxian.md
      - 千岛湖: shihua/shi/qiandaohu.md
      - 滕州: shihua/shi/tengzhou.md
      - 如果我是: shihua/shi/ruguowoshi.md
      - 你说，你想去看海: shihua/shi/kanhai.md
      - 盼暖春来: shihua/shi/pannuanchunlai.md
      - 想有个房间: shihua/shi/fangjian.md
      - 一剪梅: shihua/shi/yijianmei.md
      - 南丁格尔的脚印: shihua/shi/ndge.md
      - 我曾: shihua/shi/woceng.md
      - 记UZI最后一次复出: shihua/shi/uzi.md
    - 画意:
      - C:
        - 枯木: shihua/hua/c/kumu.md
        - 大圣归来: shihua/hua/c/dasheng.md
        - 我爱罗/鼬: shihua/hua/c/gaara.md
        - 织田信长: shihua/hua/c/xinchang.md
        - 金木研: shihua/hua/c/jinmuyan.md
      - S:
        - 2018-08-29: shihua/hua/s/20180829.md
        - 2020-11-19: shihua/hua/s/20201119.md
        - 2020-11-20: shihua/hua/s/20201120.md
        - 2020-11-27: shihua/hua/s/20201127.md
        - 2020-11-30: shihua/hua/s/20201130.md
        - 2020-12-05: shihua/hua/s/20201205.md
        - 2021-09-05: shihua/hua/s/20210905.md
        - 2021-10-10: shihua/hua/s/20211010.md
        - 2021-10-17: shihua/hua/s/20211017.md
        - 2022-02-19: shihua/hua/s/20220219.md
        - 2022-03-14: shihua/hua/s/20220314.md
        - 2022-03-15: shihua/hua/s/20220315.md
        - 2022-03-19: shihua/hua/s/20220319.md
        - 2022-03-26: shihua/hua/s/20220326.md
        - 2022-03-27: shihua/hua/s/20220327.md
        - 2022-04-02: shihua/hua/s/20220402.md
        - 2022-04-04: shihua/hua/s/20220404.md
        - 2022-04-05: shihua/hua/s/20220405.md
        - 2022-04-06: shihua/hua/s/20220406.md
        - 2022-04-10: shihua/hua/s/20220410.md
        - 2022-04-30: shihua/hua/s/20220430.md
        - 2022-05-03: shihua/hua/s/20220503.md
        - 2022-05-04: shihua/hua/s/20220504.md
        - 2022-05-14: shihua/hua/s/20220514.md
        - 2022-05-15: shihua/hua/s/20220515.md
        - 2025-06-16: shihua/hua/s/20250616.md
  - 演唱会:
    - 演唱会: yanchanghui/index.md
    - 2019:
      - 房东的猫·2019南京: yanchanghui/ych/fddm2019.md
    - 2022:
      - 新裤子·2022苏州: yanchanghui/ych/xkz2022.md
    - 2023:
      - 伍佰·2023上海: yanchanghui/ych/wb2023.md
    - 2024:
      - 紫琅音乐节·2024南通: yanchanghui/ych/ntzl2024.md
      - 周传雄·2024上海: yanchanghui/ych/zcx2024.md
    - 2025:
      - 谢天笑·2024上海: yanchanghui/ych/xtx2024.md
      - 张韶涵·2025昆山: yanchanghui/ych/zsh2025.md
  - 是博主呀:
    - 是博主呀: shibozhuya/index.md
    #- 哔哩哔哩:
    - 抖音: shibozhuya/sbzy/douyin.md
    #- 西瓜:
    - 知乎: shibozhuya/sbzy/zhihu.md
    #- 画吧:
    - 哔哩哔哩: shibozhuya/sbzy/bilibili.md
    
      
theme:
  name: material
  custom_dir: docs/res/overrides
  logo: res/icons/CSheart2.svg
  favicon: res/icons/CSheart2.svg
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 关闭自动模式
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: 'cyan' # 主题颜色
      accent: 'orange' # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-sunny 
        name: 切换至夜间模式 # 鼠标悬浮提示
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black # 主题颜色
      accent: indigo
      toggle:
        icon: material/weather-night 
        name: 切换至日间模式 # 鼠标悬浮提示

    
  features:
    - navigation.top
    - navigation.footer
    - navigation.path
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.indexes
    - toc.integrate
    # - search.share
    - search.highlight
    - search.suggest
    - announce.dismiss
  
  language: zh
  icon:
    repo: heart #右上角图标fontawesome/brands/github
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css:  fontawesome/brands/css3
      Mkdocs: octicons/tag-16    
    
# edit_uri: edit/main/docs # 编辑按钮跳转的链接 
repo_url: https://space.bilibili.com/2069187267?spm_id_from=333.1007.0.0 # 右上角点击跳转的链接
repo_name: 跳跳之家 # 右上角的名字


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      #options:
        #custom_icons:
          #- docs/res/overrides/.icons
  - pymdownx.arithmatex:
      generic: true
  - meta
  - toc:
      toc_depth: 2
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - javascripts/katex.js
  #- https://cdn.auth0.com/js/auth0-spa-js/1.2/auth0-spa-js.production.js
  #- javascripts/auth.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

plugins:
  - search
  

extra_css:
  - res/stylesheets/extra.css
  - res/stylesheets/customize.css  #按钮圆角化
  - res/stylesheets/bannerSlider.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-lite-webfont@1.1.0/style.css
  - https://unpkg.com/katex@0/dist/katex.min.css


extra:
  #generator: false
  alternate:
    #- name: English
      #link: ../en/ 
      #lang: en
    - name: 中文
      link: ../zh/
      lang: zh
  social:
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/2069187267?spm_id_from=333.1007.0.0
      name: 一颗麦子呀
    - icon: fontawesome/brands/tiktok
      link: https://www.douyin.com/user/MS4wLjABAAAAXD3xE4ARhbdpqQvDvQPzN3oHenEyIBdWzGV5GYHRosqGUn8nvJuz1aoPVScoUCX1?from_tab_name=main&is_search=0&list_name=follow&nt=0
      name: 是麦子呀
    - icon: fontawesome/brands/tiktok
      link: https://www.douyin.com/user/MS4wLjABAAAA3shEtLqFq7-HiGjmUL-4t_qiv4qn_aGLh2VGj0Cj7tFDu7Bt5x-hbZ_VCyhDfA4Z?from_tab_name=main&is_search=0&list_name=follow&nt=0
      name: 麦子黄了
    - icon: xigua2
      link: https://www.ixigua.com/home/339097487425336/?list_entrance=search
      name: 小麦子跳跳日食记
    - icon: simple/zhihu #fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/zhi-yi-73-45
      name: 只一
  
  
copyright: Copyright © 2024 跳跳之家版权所有 | <a href="/legal/copyright/">硕总专属</a>



